name: release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Create archive
        run: zip -r minecraft-ainu.zip pack/

      - name: Upload asset
        run: gh release upload "${{ github.ref_name }}" minecraft-ainu.zip --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
